
package org.csapi.wsdl.transaction.data.v1_0._interface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.csapi.schema.transaction.data.v1_0.local.QueryTranscation;
import org.csapi.schema.transaction.data.v1_0.local.QueryTranscationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryTransactionPort", targetNamespace = "http://www.csapi.org/wsdl/transaction/data/v1_0/interface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.csapi.schema.transaction.data.v1_0.local.ObjectFactory.class,
    com.vodafone.mm.gen.api_v1.mminterface.result.ObjectFactory.class,
    cn.com.huawei.schema.common.v2_1.ObjectFactory.class,
    com.vodafone.mm.gen.api_v1.mminterface.response.ObjectFactory.class
})
public interface QueryTransactionPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.csapi.schema.transaction.data.v1_0.local.QueryTranscationResponse
     */
    @WebMethod
    @WebResult(name = "queryTranscationResponse", targetNamespace = "http://www.csapi.org/schema/transaction/data/v1_0/local", partName = "result")
    public QueryTranscationResponse queryTransaction(
        @WebParam(name = "queryTranscation", targetNamespace = "http://www.csapi.org/schema/transaction/data/v1_0/local", partName = "parameters")
        QueryTranscation parameters);

}
