
package org.csapi.wsdl.transaction.data.v1_0._interface;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QueryTransactionService", targetNamespace = "http://www.csapi.org/wsdl/transaction/data/v1_0/interface", wsdlLocation = "file:/home/oyugik/Desktop/PURPLE/MNO/Safaricom/QueryTransaction_1_0.wsdl")
public class QueryTransactionService
    extends Service
{

    private final static URL QUERYTRANSACTIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.csapi.wsdl.transaction.data.v1_0._interface.QueryTransactionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.csapi.wsdl.transaction.data.v1_0._interface.QueryTransactionService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/oyugik/Desktop/PURPLE/MNO/Safaricom/QueryTransaction_1_0.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/oyugik/Desktop/PURPLE/MNO/Safaricom/QueryTransaction_1_0.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYTRANSACTIONSERVICE_WSDL_LOCATION = url;
    }

    public QueryTransactionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryTransactionService() {
        super(QUERYTRANSACTIONSERVICE_WSDL_LOCATION, new QName("http://www.csapi.org/wsdl/transaction/data/v1_0/interface", "QueryTransactionService"));
    }

    /**
     * 
     * @return
     *     returns QueryTransactionPort
     */
    @WebEndpoint(name = "queryTransaction")
    public QueryTransactionPort getQueryTransaction() {
        return super.getPort(new QName("http://www.csapi.org/wsdl/transaction/data/v1_0/interface", "queryTransaction"), QueryTransactionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryTransactionPort
     */
    @WebEndpoint(name = "queryTransaction")
    public QueryTransactionPort getQueryTransaction(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csapi.org/wsdl/transaction/data/v1_0/interface", "queryTransaction"), QueryTransactionPort.class, features);
    }

}
